### ISSUE TITLE
How to plot task affinity scores in Figure 1.

### ISSUE THREAD

**Issue by RachelTeamo** [gohyojun15/ANT_diffusion#1]
Thanks for sharing the code, ANT is a great work of theoretical analysis of diffusion models. 
I am curious how Figure 1 of the paper was plotted, it would be great if you could share the code for plotting it.

**Comment by gohyojun15** [comment]
Thank you for raising the issue!.
Since my affiliation is changed during the neurips review process of our paper, some parts of my code are lost.
Therefore, releasing it at now is quite difficult to me!.

Relying on my memory, I will reimplement and update codes for task affinity scores.
Note that resulting implementation can be different from codes originally used in my original paper.

**Comment by gohyojun15** [comment]
I will finish this in one week!

**Comment by gohyojun15** [comment]
Could you check https://github.com/gohyojun15/ANT_diffusion/blob/main/task_affinity_score.py?
I implemented a task affinity score calculation there.
You can change some configurations for calculation, and I remember there are no significant differences in approximating its calculation.
For example, grouping timesteps in small intervals (e.g. 10 timesteps per group) and calculating task affinity scores produces faster computation, but no significant difference.

If you have further questions, please feel free to ask!
